# more details of settings in https://coverage.readthedocs.io/en/coverage-5.5/config.html
#
# coverage run -m pytest . && coverage html && open .coverage_html/index.html
#
[tool.coverage.run]
source = ["computerSitTimer"]
omit = [
    "**/__init__.py",
    "**/__main__.py",
    "**/Tests/*",
    "**/tmp*",
]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",
    # Don't complain about missing debug-only code:
    "def __repr__",
    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",
    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if False:",
    "if __name__ == .__main__.:",
]

[tool.coverage.html]
directory = ".coverage_html"

[tool.coverage.xml]
directory = "coverage.xml"
