# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# good examples from https://github.com/nedbat/coveragepy/tree/master/.github/workflows
  .github/workflows/testsuite.yml
name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        exclude:
          # Windows does not have PySide for py3.10
          - os: windows-latest
            python-version: "3.10"
          # macOS has AttributeError: 'QT_QMainWindowClass' object has no attribute 'setWindowFlags'
          - os: macos-latest
            python-version: "3.10"
      fail-fast: false

    steps:
      - name: "Check out repo"
        uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install dependencies"
        run: pip install -r requirements.txt

      - name: "Test with pytest"
        run: pytest
